### ISSUE TITLE
(Trac #115) Test failures on lenny/armel

### ISSUE THREAD

**Issue by foolscap-trac** [foolscap-trac/test-foolscap-import-4#118]
| <img alt="Zandr's avatar" src="https://avatars.githubusercontent.com/u/224017?v=4" width="50" height="50"> | trac:Zandr reported |
|-|-|
| Trac ID | trac#115 |
| Type | defect |
| Created | 2009-03-07 03:03:21Z |
| Version | 0.3.0 |
| Resolution | fixed |

This is worse than I recall, but that might be due to timeouts caused by competing with a cryptopp compile on a very feeble host. :)

```

===============================================================================
[FAIL]: foolscap.test.test_logging.Publish.test_logpublisher

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/foolscap-0.3.2-py2.5.egg/foolscap/test/test_logging.py", line 527, in _check_observer
    self.failUnlessEqual(len(msgs), 8)
twisted.trial.unittest.FailTest: not equal:
a = 0
b = 8

===============================================================================
[FAIL]: foolscap.test.test_logging.Publish.test_logpublisher_catchup

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/foolscap-0.3.2-py2.5.egg/foolscap/test/test_logging.py", line 690, in _check_observer
    self.failUnless(len(msgs) >= 2, len(msgs))
twisted.trial.unittest.FailTest: 0
===============================================================================
[FAIL]: foolscap.test.test_negotiate.Crossfire.test4

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/foolscap-0.3.2-py2.5.egg/foolscap/test/test_negotiate.py", line 563, in checkConnectedViaReverse
    self.tub2.getListeners()[0].getPortnum())
twisted.trial.unittest.FailTest: not equal:
a = 50230
b = 46998

===============================================================================
[FAIL]: foolscap.test.test_pb.TestService.testBadMethod

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/foolscap-0.3.2-py2.5.egg/foolscap/test/test_pb.py", line 648, in _testBadMethod_eb
    self.failUnlessEqual(f.type, Violation)
twisted.trial.unittest.FailTest: not equal:
a = <class 'foolscap.tokens.NegotiationError'>
b = <class 'foolscap.tokens.Violation'>

===============================================================================
[ERROR]: foolscap.test.test_gifts.Bad.test_tubid

Traceback (most recent call last):
Failure: foolscap.tokens.NegotiationError: no connection established within client timeout
===============================================================================
[ERROR]: foolscap.test.test_negotiate.Crossfire.test4

Traceback (most recent call last):
Failure: foolscap.ipb.DeadReferenceError: Connection was lost
===============================================================================
[ERROR]: foolscap.test.test_pb.TestCallable.testFunction

Traceback (most recent call last):
Failure: foolscap.tokens.NegotiationError: no connection established within client timeout
===============================================================================
[ERROR]: foolscap.test.test_pb.TestCallable.testLogLocalFailure

Traceback (most recent call last):
Failure: foolscap.tokens.NegotiationError: no connection established within client timeout
===============================================================================
[ERROR]: foolscap.test.test_pb.TestCallable.testLogRemoteFailure

Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <foolscap.test.test_pb.TestCallable testMethod=testLogRemoteFailure> (testLogRemoteFailure) still running at 2.0 secs
===============================================================================
[ERROR]: foolscap.test.test_pb.TestCallable.testLogRemoteFailure

Traceback (most recent call last):
Failure: foolscap.tokens.NegotiationError: no connection established within client timeout
===============================================================================
[ERROR]: foolscap.test.test_pb.TestService.testBadMethod2

Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <foolscap.test.test_pb.TestService testMethod=testBadMethod2> (testBadMethod2) still running at 5.0 secs
-------------------------------------------------------------------------------
Ran 415 tests in 2312.232s

FAILED (skips=4, failures=4, errors=7, successes=403)
```

**Comment by foolscap-trac** [comment]
| <img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?v=4" width="50" height="50"> | trac:zooko commented |
|-|-|

We need a foolscap buildbot.

**Comment by foolscap-trac** [comment]
| <img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?v=4" width="50" height="50"> | trac:warner commented |
|-|-|

this is ancient, lenny is no more, we've got a buildbot that's green. I feel pretty safe closing this one now :)

**Comment by foolscap-trac** [comment]
| <img alt="warner's avatar" src="https://avatars.githubusercontent.com/u/27146?v=4" width="50" height="50"> | trac:warner set resolution to `fixed` |
|-|-|
